---
version: '3'
services:
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - /tmp/logs/:/tmp/logs/:rw

  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - /tmp/logs/:/tmp/logs/:rw

networks:
  default:
    external:
      name: confluent_default